#!/bin/sh
set -eu
mkdir -p /run/alpenglow
if [ -s /etc/alpenglow/role ]; then
  cp /etc/alpenglow/role /run/alpenglow/role
fi
if [ -s /etc/alpenglow/edition ]; then
  cp /etc/alpenglow/edition /run/alpenglow/edition
fi
if [ -s /etc/alpenglow/sku ]; then
  cp /etc/alpenglow/sku /run/alpenglow/sku
fi
exit 0
