#!/bin/sh
args=""
for arg in "$@"; do
  case "$arg" in
    --target=x86_64-unknown-linux-musl) ;;
    *) args="$args $(printf '%s' "$arg" | sed "s/'/'\\\\''/g; s/.*/'&'/")" ;;
  esac
done
eval exec zig c++ -target x86_64-linux-musl $args
