#!/bin/sh
# Validate Alpenglow kernel config has required options and no forbidden ones
set -eu

CONFIG="${1:-$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)/alpenglow-internet-appliance.config}"
[ -f "$CONFIG" ] || { echo "missing: $CONFIG"; exit 1; }

failures=0
check() {
  local op="$1" opt="$2"
  local val
  val=$(awk -v opt="$opt" '$0 ~ "^" opt "=" { v=substr($0,index($0,"=")+1); print v } $0 == "# " opt " is not set" { print "n" } END { if(v=="") print "n" }' "$CONFIG")

  if [ "$op" = "y" ]; then
    [ "$val" = "y" ] || [ "$val" = "m" ] || { echo "MISSING: $opt"; failures=$((failures+1)); }
  elif [ "$op" = "n" ]; then
    [ "$val" = "n" ] || { echo "MUST BE OFF: $opt (found $val)"; failures=$((failures+1)); }
  fi
}

# Required (y or m)
for opt in CONFIG_CGROUPS CONFIG_RUST CONFIG_CGROUP_BPF CONFIG_CGROUP_PIDS CONFIG_CPUSETS \
  CONFIG_MEMCG CONFIG_LRU_GEN CONFIG_LRU_GEN_ENABLED CONFIG_BLK_CGROUP CONFIG_NAMESPACES \
  CONFIG_SECCOMP CONFIG_SECCOMP_FILTER CONFIG_SECURITY_LANDLOCK CONFIG_NET_SCH_FQ \
  CONFIG_TCP_CONG_BBR CONFIG_ZRAM CONFIG_ZSMALLOC CONFIG_SWAP CONFIG_EROFS_FS \
  CONFIG_EROFS_FS_ZIP CONFIG_VIRTIO CONFIG_VIRTIO_PCI CONFIG_VIRTIO_BLK CONFIG_VIRTIO_NET \
  CONFIG_VIRTIO_CONSOLE CONFIG_HW_RANDOM_VIRTIO CONFIG_DRM CONFIG_DRM_KMS_HELPER \
  CONFIG_DRM_FBDEV_EMULATION CONFIG_DRM_VIRTIO_GPU CONFIG_DRM_SIMPLEDRM CONFIG_EXT4_FS \
  CONFIG_SQUASHFS CONFIG_SQUASHFS_ZSTD CONFIG_OVERLAY_FS CONFIG_TMPFS CONFIG_DEVTMPFS \
  CONFIG_DEVTMPFS_MOUNT; do
  check y "$opt"
done

# Forbidden
for opt in CONFIG_ACPI CONFIG_ANDROID CONFIG_APPLETALK CONFIG_ATM CONFIG_BCACHEFS_FS \
  CONFIG_BFS_FS CONFIG_BLUETOOTH CONFIG_BTRFS_FS CONFIG_CAN CONFIG_CEPH_FS CONFIG_CIFS \
  CONFIG_DLM CONFIG_DRM_NOUVEAU CONFIG_DRM_RADEON CONFIG_DRM_XE CONFIG_FIREWIRE \
  CONFIG_GFS2_FS CONFIG_HAMRADIO CONFIG_HFS_FS CONFIG_HFSPLUS_FS CONFIG_INFINIBAND \
  CONFIG_IP_DCCP CONFIG_IP_SCTP CONFIG_IPX CONFIG_ISDN CONFIG_JFS_FS CONFIG_NFC \
  CONFIG_NFS_FS CONFIG_OCFS2_FS CONFIG_PPP CONFIG_REISERFS_FS CONFIG_SCSI \
  CONFIG_SMB_SERVER CONFIG_SOUND CONFIG_USB_GADGET CONFIG_USB_STORAGE CONFIG_WIMAX \
  CONFIG_WIRELESS_EXT CONFIG_X25; do
  check n "$opt"
done

[ "$failures" -eq 0 ] || { echo "FAILED: $failures errors"; exit 1; }
echo "ok $CONFIG"
